<?php

namespace App\Entities;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Tag extends Model implements Transformable
{
    use TransformableTrait;

    public $table = 'tags';

    protected $fillable = ['name'];

    protected $dates = ['deleted_at'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //软删除关联模型
        self::deleting(function($model){
           $model->articleTag()->detach();
           $model->downloadTag()->detach();
           $model->pictureTag()->detach();
           $model->vidioTag()->detach();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function articleTag(){
        return $this->belongsToMany('App\Entities\ArticleTag', 'article_tags');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function downloadTag(){
        return $this->belongsToMany('App\Entities\DownloadTag', 'download_tags');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function pictureTag(){
        return $this->belongsToMany('App\Entities\PictureTag', 'picture_tags');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function vidioTag(){
        return $this->belongsToMany('App\Entities\VidioTag', 'vidio_tags');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tagArticleTag(){
        return $this->hasMany('App\Entities\ArticleTag', 'tag_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tagPictureTag(){
        return $this->hasMany('App\Entities\PictureTag', 'tag_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tagDownloadTag(){
        return $this->hasMany('App\Entities\DownloadTag', 'tag_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tagVidioTag(){
        return $this->hasMany('App\Entities\VidioTag', 'tag_id', 'id');
    }
}
